// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestPossumus.UnitOfWork;

#nullable disable

namespace TestPossumus.Migrations
{
    [DbContext(typeof(ApiBDContext))]
    [Migration("20221205142051_ApiPossumusMigration")]
    partial class ApiPossumusMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestPossumus.UnitOfWork.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaDeNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("IdEmpleo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Telefono")
                        .HasColumnType("numeric(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleo");

                    b.ToTable("Candidato", (string)null);
                });

            modelBuilder.Entity("TestPossumus.UnitOfWork.Empleo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreEmpresa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre-Empresa");

                    b.Property<string>("Periodo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empleo", (string)null);
                });

            modelBuilder.Entity("TestPossumus.UnitOfWork.Candidato", b =>
                {
                    b.HasOne("TestPossumus.UnitOfWork.Empleo", "IdEmpleoNavigation")
                        .WithMany("Candidatos")
                        .HasForeignKey("IdEmpleo")
                        .HasConstraintName("FK_Candidato_Empleo");

                    b.Navigation("IdEmpleoNavigation");
                });

            modelBuilder.Entity("TestPossumus.UnitOfWork.Empleo", b =>
                {
                    b.Navigation("Candidatos");
                });
#pragma warning restore 612, 618
        }
    }
}
